---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: keel
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`keel.example.com`)
      kind: Rule
      services:
        - name: keel
          port: 9300
